version: "3"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/tools/kkaneko.42.fr:/var/www/

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "3306:3306"
    volumes:
      - ./requirements/wordpress/src:/var/www/
    tty: true
    stdin_open: true

