version: '3'
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - CERTS=${CERTS}
    volumes:
      - ./requirements/tools/htdocs:/var/www/kkaneko.42.fr/htdocs
    ports:
      - 443:443
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - ./requirements/tools/htdocs:/var/www/kkaneko.42.fr/htdocs

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
