version: "3"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/tools/kkaneko.42.fr:/var/www/

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./requirements/wordpress/src:/var/www/src
    tty: true
    stdin_open: true

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    tty: true
    stdin_open: true
